# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"X\n\x0bVoteRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x15\n\rLast_Log_Term\x18\x03 \x01(\x05\x12\x13\n\x0bLast_Log_Id\x18\x04 \x01(\x05\"$\n\x0cVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\"\x91\x01\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x45ntries\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x16\n\x0e\x44\x65stination_Id\x18\x04 \x01(\x05\x12\x15\n\rPrev_Log_Term\x18\x05 \x01(\x05\x12\x13\n\x0bPrev_Log_Id\x18\x06 \x01(\x05\x12\x16\n\x0eLeader_Commite\x18\x07 \x01(\x05\"!\n\x0e\x41ppendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32z\n\x0bRaftService\x12\x34\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12\x35\n\rAppendEntries\x12\x0e.raft.LogEntry\x1a\x14.raft.AppendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=108
  _globals['_VOTERESPONSE']._serialized_start=110
  _globals['_VOTERESPONSE']._serialized_end=146
  _globals['_LOGENTRY']._serialized_start=149
  _globals['_LOGENTRY']._serialized_end=294
  _globals['_APPENDRESPONSE']._serialized_start=296
  _globals['_APPENDRESPONSE']._serialized_end=329
  _globals['_RAFTSERVICE']._serialized_start=331
  _globals['_RAFTSERVICE']._serialized_end=453
# @@protoc_insertion_point(module_scope)
